### PR TITLE
Release docs and changelog

### PR DESCRIPTION
**Pull request by obilodeau**
Once accepted, I'll cut the releases in GitHub's UI.

Chose AsciiDoc over markdown because that's already what I maintain with Malboxes and Asciidoctor-reveal.js. Similar release steps and strategies both under SemVer.

### CODE REVIEW

**Comment by xshill** [comment]
We're gonna have both asciidoc and markdown? :thinking: That seems strange to me.

**Comment by obilodeau** [comment]
I don't see a problem with adding AsciiDoc to Markdown, especially since we are a bigger AsciiDoc shop than markdown and that former format is superior in conciseness.

The project already has reStructuredText docstrings. If having multiple formats would be a real problem shouldn't we have used a reStructuredText README instead of Markdown? So this means multiple formats is ok.

Lastly, as I already stated all my release reflexes (malboxes, asciidoctor-reveal.js) are around AsciiDoc so I'm saving time by using AsciiDoc instead of markdown.

**Comment by Res260** [comment]
Didnt know reStructuredText was meant for readme as well :o

--Émilio

**Comment by obilodeau** [comment]
Releases were cut: https://github.com/GoSecure/pyrdp/releases

**Pull request merged**
