### PR TITLE
Add a CI badge in the readme

### PR DESCRIPTION
**Pull request by Res260**
Just discovered this felt the need to add it

image

### CODE REVIEW

**Comment by Res260** [comment]
just looked at the diff its vscode's fault :(

**Comment by Res260** [comment]
@alxbl Yeah we would need to change the `name` in CI.yml to `Build` and then change the url of the badge.

**Comment by alxbl** [comment]
If it's not too much a hassle, I'd rather have the badge be called "Build" since that's what most people expect and what most projects use.

**Comment by Res260** [comment]
done @alxbl

**Comment by Res260** [comment]
(should be squashed)

**Pull request merged**
