### PR TITLE
Use proper progress bar for MP4 conversion. Fixes #274.

### LINKED ISSUE #274: MP4 conversion - use proper progress bar
Currently, the `pyrdp-convert` shows a "bouncing ball" type of progress bar, which provides no useful information. Using a regular progress bar would:

- Give the user an idea of how much of the replay has been processed
- Give the user an estimation of how long it will take to convert the replay (which is handled automatically by the `progressbar` module)

Considering that rendering MP4s can take a while, it would be nice to provide this information to users so they're not left in the dark.

### PR DESCRIPTION
**Pull request by xshill**
See issue #274.

### CODE REVIEW

**Comment by obilodeau** [comment]
This is a significantly larger PR than I expected. I don't have time to review it right now. There are some weirds things (ie: duplicated imports) in there that looks like a previous merge was botched and it bothers me. Did you track this down?

**Comment by xshill** [comment]
It seems like they were from PR #257 : https://github.com/GoSecure/pyrdp/commit/6d94bc538f266d16c69091770548d1431cce7c67

**Comment by obilodeau** [comment]
Those damn merges... I missed that in review.

**Review by obilodeau — APPROVED** [review]
LGTM! The `ReplayReader` is a bit convoluted for the casual dev that I am but I'm sure you could explain it to me in our next meeting :wink:

**Pull request merged**
