### PR TITLE
Add a connection time log statement upon client disconnection

### PR DESCRIPTION
**Pull request by Res260**
Implements #111

### CODE REVIEW

**Comment by xshill** [comment]
The commit name and change are completely unrelated?

**Comment by Res260** [comment]
Damn I pushed the wrong thing, I'll fix that soon

**Comment by xshill** [comment]
The changes seem right, it's just the message that's wrong.

**Comment by Res260** [comment]
I opened a separate PR for those changes

**Comment by Res260** [comment]
Ok nevermind I simply got confused.

**Pull request merged**
